export const questions = [
  {
    format: "Trivia",
    country: "India",
    prompt: "During Garba, dancers traditionally move in circles around a central object. What is it?",
    options: ["A clay lamp (diva)", "A brass pot with a lamp (garbo)", "A wooden idol", "A basket of flowers"],
    correct: 1,
    explain: "The garbo, a perforated clay or brass pot lit with a lamp inside, represents the womb of life and sits at the centre during Navratri Garba.",
  },
  {
    format: "Trivia",
    country: "Mauritius",
    prompt: "Sega, Mauritius's most iconic music and dance style, historically originated among which group?",
    options: ["Enslaved and indentured communities", "French colonial navy bands", "Tourist resort performers", "Fishermen's trade unions"],
    correct: 0,
    explain: "Sega grew out of the songs and dances of enslaved Africans and later indentured labourers, and remains central to Mauritian identity today.",
  },
  {
    format: "Spot the Myth",
    country: "Mauritius",
    prompt: "Which one of these is NOT true about Mauritius?",
    options: [
      "It has no official state religion and celebrates Hindu, Christian, and Muslim holidays as public holidays",
      "Mauritian Creole (Kreol Morisien) is the most widely spoken language at home",
      "It is a landlocked country in East Africa",
      "The dodo, now extinct, was native only to Mauritius",
    ],
    correct: 2,
    explain: "Mauritius is an island nation in the Indian Ocean, not landlocked — it's roughly 2,000 km off the southeast coast of Africa.",
  },
  {
    format: "Trivia",
    country: "India",
    prompt: "Gujarat's Rann of Kutch hosts a major winter festival on a seasonal salt marsh. What is it called?",
    options: ["Rann Utsav", "Kutch Mahotsav", "Sindhu Darshan", "Sharad Purnima"],
    correct: 0,
    explain: "Rann Utsav is a months-long festival on the white salt desert, featuring handicrafts, folk music, and moonlit camping.",
  },
  {
    format: "Trivia",
    country: "Mauritius",
    prompt: "What is 'dholl puri', arguably Mauritius's most popular street food?",
    options: [
      "A sweet coconut dumpling",
      "A flatbread stuffed with ground yellow split peas, served with curry",
      "A grilled fish skewer",
      "A rice and lentil porridge eaten at breakfast",
    ],
    correct: 1,
    explain: "Dholl puri shows Mauritius's Indo-Mauritian heritage: a thin flatbread filled with spiced split-pea paste, folded and topped with curries and chutneys.",
  },
  {
    format: "Spot the Myth",
    country: "India",
    prompt: "Which one of these is NOT true about Gujarati culture?",
    options: [
      "Gujarati cuisine is famous for its use of jaggery to balance sweet and savoury flavours",
      "Gujarat is the birthplace of Mahatma Gandhi",
      "Gujarati is written in the Devanagari script, identical to Hindi",
      "The Kite Festival (Uttarayan) is a major celebration in Gujarat",
    ],
    correct: 2,
    explain: "Gujarati has its own script, distinct from Devanagari, even though both descend from a shared ancestor and share some visual similarity.",
  },
  {
    format: "Trivia",
    country: "Both",
    prompt: "Both India and Mauritius share which of these cultural connections?",
    options: [
      "A common official language",
      "A large population of Indian-origin residents in Mauritius due to 19th-century indentured labour migration",
      "The same national flower",
      "A shared land border",
    ],
    correct: 1,
    explain: "After slavery was abolished, thousands of Indian indentured labourers, many from Bihar and other regions, were brought to Mauritius, shaping its demographics and culture ever since.",
  },
  {
    format: "Trivia",
    country: "Mauritius",
    prompt: "What does the Mauritian holiday 'Cavadee', observed by the Tamil community, involve?",
    options: [
      "A silent meditation retreat",
      "Devotees carrying decorated wooden arches (kavadi) as an act of devotion, sometimes after fasting",
      "A national kite-flying competition",
      "A boat race across the lagoon",
    ],
    correct: 1,
    explain: "Cavadee is a Tamil Hindu festival where devotees carry kavadi (semi-circular decorated structures) in devotion to Lord Muruga, often after days of fasting and prayer.",
  },
  {
    format: "Spot the Myth",
    country: "India",
    prompt: "Which one of these is NOT true about Navratri celebrations?",
    options: [
      "Navratri means 'nine nights' and honours the goddess Durga in her different forms",
      "Garba and Dandiya Raas are traditional dance forms performed during Navratri",
      "Navratri is celebrated only in Gujarat and nowhere else in India",
      "Fasting for all or part of the nine days is common during Navratri",
    ],
    correct: 2,
    explain: "Navratri is celebrated across India (and by the Indian diaspora worldwide) with regional variations — it's far from exclusive to Gujarat, though Garba is especially associated with it.",
  },
  {
    format: "Trivia",
    country: "Mauritius",
    prompt: "What are the three official/widely used languages you're most likely to hear in a Mauritian classroom or shop?",
    options: [
      "English, French, and Mauritian Creole",
      "Portuguese, Swahili, and English",
      "Hindi, Tamil, and Arabic only",
      "Dutch, Malagasy, and French",
    ],
    correct: 0,
    explain: "English is the official language of government and schooling, French is widely used in media and daily life, and Mauritian Creole (Kreol Morisien) is the most common home language.",
  },
  {
    format: "Trivia",
    country: "India",
    prompt: "What is 'dhokla', a Gujarati dish often introduced to newcomers first?",
    options: [
      "A deep-fried spiced pastry",
      "A steamed, spongy savoury cake made from fermented rice and chickpea flour batter",
      "A sweet milk-based dessert",
      "A dry-roasted lentil snack mix"
    ],
    correct: 1,
    explain: "Dhokla is steamed rather than fried, made from a fermented gram-flour batter, and is a signature light, tangy Gujarati snack.",
  },
  {
    format: "Spot the Myth",
    country: "Mauritius",
    prompt: "Which one of these is NOT true about Mauritian food culture?",
    options: [
      "Mauritian cuisine blends African, Indian, Chinese, and French influences",
      "Rougaille, a tomato-based Creole sauce, is a staple in many Mauritian households",
      "Mauritius has no Chinese-influenced dishes since there was never a Chinese community there",
      "Alouda, a rose-flavoured milk drink with basil seeds, is a popular Mauritian beverage",
    ],
    correct: 2,
    explain: "Sino-Mauritians have been part of the island since the 18th–19th centuries, and Chinese-influenced dishes like mine frite (fried noodles) are everyday Mauritian food.",
  },
  {
    format: "Trivia",
    country: "India",
    prompt: "What does the term 'jugaad', often used across India including Gujarat, generally mean?",
    options: [
      "A formal legal contract",
      "A flexible, resourceful fix or workaround using limited means",
      "A type of classical dance",
      "A government subsidy scheme",
    ],
    correct: 1,
    explain: "Jugaad refers to an improvised, low-cost solution to a problem — a widely celebrated form of everyday creativity and resourcefulness.",
  },
  {
    format: "Trivia",
    country: "Mauritius",
    prompt: "Port Louis, the capital of Mauritius, is home to which famous market building dating to the 19th century?",
    options: ["The Central Market (Port Louis Market)", "The Grand Bazaar", "The Colonial Exchange", "The Sugar House"],
    correct: 0,
    explain: "The Central Market in Port Louis has operated since the 1800s and remains a hub for fresh produce, spices, and local crafts.",
  },
  {
    format: "Spot the Myth",
    country: "Both",
    prompt: "Which one of these is NOT a shared value commonly emphasised in both Gujarati and Mauritian cultures?",
    options: [
      "Strong emphasis on hospitality and welcoming guests generously",
      "Importance of extended family and community ties",
      "A cultural preference for isolation from other communities",
      "Respect for religious and festival traditions passed down through generations",
    ],
    correct: 2,
    explain: "Both cultures are known for the opposite: multicultural coexistence and hospitality — Mauritius's motto is 'Star and Key of the Indian Ocean', reflecting its blended, welcoming identity, and Gujarati hospitality ('Atithi Devo Bhava') treats guests as god.",
  },
  {
    format: "Trivia",
    country: "India",
    prompt: "Modhera, a town in Gujarat, is home to which UNESCO-recognised heritage site?",
    options: ["The Sun Temple", "The Lotus Temple", "The Golden Temple", "The Iron Pillar"],
    correct: 0,
    explain: "The Sun Temple at Modhera, built in the 11th century, is dedicated to the sun god Surya and is renowned for its intricate stone carvings.",
  },
];
